pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    // TODO (fabi755): This is currently failing, when JS support is enabled
//    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "maplibre-java"
println('MapLibre Java combined build initializing')

include 'services-geojson'
include 'services-turf'
