apply plugin: 'maven-publish'
apply plugin: 'signing'

apply from: file("${rootDir}/gradle/artifact-settings.gradle")
apply from: file("${rootDir}/gradle/publish-root.gradle")

// Define group & version for Kotlin Multiplatform artifacts
group = project.ext.mapLibreArtifactGroupId
version = project.ext.versionName

publishing {
    publications.withType(MavenPublication) {
        groupId project.ext.mapLibreArtifactGroupId
        version project.ext.versionName

        // Drop the `services` from artifact ID
        artifactId artifactId.replace("services-", "")

        project.logger.info("Publishing project $artifactId with version: ${version}")

        pom {
            name = project.ext.mapLibreArtifactTitle
            description = project.ext.mapLibreArtifactTitle
            url = project.ext.mapLibreArtifactUrl
            licenses {
                license {
                    name = project.ext.mapLibreArtifactLicenseName
                    url = project.ext.mapLibreArtifactLicenseUrl
                }
            }
            developers {
                developer {
                    id = project.ext.mapLibreDeveloperId
                    name = project.ext.mapLibreDeveloperName
                    email = 'team@maplibre.org'
                }
            }
            scm {
                connection = project.ext.mapLibreArtifactScmUrl
                developerConnection = project.ext.mapLibreArtifactScmUrl
                url = project.ext.mapLibreArtifactUrl
            }
        }
    }
}

signing {
    required { project.ext["signing.keyId"] != null }
    sign publishing.publications
}
